spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: LEGACYHTML5
minio:
  endpoint: http://192.168.1.137:9000
  accesskey: admin
  secretKey: admin123456